### ISSUE TITLE
Depreciation is not possible on an investment account

### ISSUE THREAD

**Issue by janpieterz** [JeremyMiller/ballistic#10]
On an investment account it should be possible to amount for a depreciation instead of a Growth/Withdrawal.

**Comment by JeremyMiller** [comment]
Depreciation is supposed to be accounted for by entering negative growth amounts. However, this could be made more clear. I think we should probably add an explanation somewhere and change the "Growth" label to something that makes this more clear, like "Growth/Depreciation" or "Net Growth".

What do you think?

**Comment by janpieterz** [comment]
Net growth sounds like a solution. Or maybe making the dropdown have a Depreciation value and converting it on the back towards a negative Growth value? I tried to fiddle around a little bit and enter a couple of possibilities using titles and/or placeholders but all of them felt a little bit awkward.

**Comment by JeremyMiller** [comment]
I just realized that it would be easier to have the user enter the current value of their investments and have the application calculate the net growth based on that, rather than have the user calculate and enter it themselves. It would be easier and would solve this issue.

**Comment by janpieterz** [comment]
Smart! I actually did the interest today for the first time and had already read your post and thought that it would be super handy! Good solution.

**Comment by janpieterz** [comment]
You could say the same about the other accounts btw (I just ran into updating my checkings account and encountered the same).
Obviously if you would do this you would take the power away from it being used as a generic finance tool where people can log all their transactions but from a more early-retirement perspective I would say it is a good bet to do though!
You could even make it possible to do it this way (just setting the new value at a certain date and then calculate the growth between) and still allow people to dig deeper if they want to, perhaps by making every account have a transaction tab that will have automatic transactions (made by updating the new values on the account page) and the ability to make manual transactions.

**Comment by JeremyMiller** [comment]
I think this solution could be useful for debts and assets, however I'd like to keep general accounts transaction based since their purpose is to make people mindful of their spending/income. Having people just enter their current balance every once and a while wouldn't be as good as actually showing them what they spent their money on in the previous month. I might still make it an option though.

Anyway, I'm going to try to get this feature done today for investment accounts at least.

**Comment by janpieterz** [comment]
Awesome, thanks! Will have my monthly status check somewhere this week, look forward to using it.
