### ISSUE TITLE
Database Creation

### ISSUE THREAD

**Issue by SirLagz** [JeremyMiller/ballistic#16]
I'm trying to dockerize ballistic, however when I try to start it after creating the container, I get this

Possibly unhandled SequelizeConnectionError: database "ballistic_development" does not exist

Is there a database creation script that I didn't run ?

**Comment by JeremyMiller** [comment]
By default, ballistic will try to connect to the "development" database declared in `config/db.json`. You can change which database it selects by entering `NODE_ENV=production` or `NODE_ENV=test` before `npm start`.

The database declared must exist and be accessible. Basically, if you're using postgres and running with the default development database, you just need to run `psql` to bring up the postgres console and then run `CREATE DATABASE ballistic_development;`. You will also need to change the username and password in `config/db.json` if you have not already.

**Comment by SirLagz** [comment]
Ah right. Didn't realise all it needed was an empty database. Thanks for that.
